### ISSUE TITLE
Sign packages

### ISSUE THREAD

**Issue by didierofrivia** [Kuadrant/helm-charts#18]
**Is your feature request related to a problem? Please describe.**
Currently our chart packages are not signed. Which means we can't guarantee the integrity of those to the users.

**Describe the solution you'd like**
Signing every package when it's created at their original repositories (authorino-operator, limitador-operator, dns-operator and kuadrant-operator) thus we not only will be guarantee the package integrity but also gaining the _Signed_ badge at [ArtifactsHub.io](https://artifacthub.io).

**TODO**
* [x] DNS Operator 
   - https://github.com/Kuadrant/dns-operator/pull/370
   - https://github.com/Kuadrant/dns-operator/pull/373
   - Release alpha
* [x] Limitador Operator 
   - https://github.com/Kuadrant/limitador-operator/pull/175
   - https://github.com/Kuadrant/limitador-operator/pull/178
   - Release alpha
* [x] Authorino Operator 
   - https://github.com/Kuadrant/authorino-operator/pull/238
   - https://github.com/Kuadrant/authorino-operator/pull/240
   - Release alpha
* [x] Kuadrant Operator
   - https://github.com/Kuadrant/kuadrant-operator/pull/1151
   - https://github.com/Kuadrant/kuadrant-operator/pull/1155
   - Release alpha
* [x] Sync provenance file from each chart - https://github.com/Kuadrant/helm-charts/pull/21
* [x] Upload kuadrant public key to kuadrant.io - https://github.com/Kuadrant/helm-charts/pull/22
* [x] Setup ArtifactsHub.io to validate signed packages

**Notes**
Here's a guide:
https://helm.sh/docs/topics/provenance/

**Comment by didierofrivia** [comment]
There's still something wrong with the kuadrant-operator, since the chart is signed when created and with the provenance file also uploaded to the repo, still not marked in ArtifactHub.io as signed. Issue tracking this: https://github.com/Kuadrant/helm-charts/issues/27
